### ISSUE TITLE
sql error

### ISSUE THREAD

**Issue by JessicaxD** [jonassvensson4/jsfour-register#1]
getting a error that identifier have no value, when try to make a character

**Comment by JessicaxD** [comment]
do i need to have esx_identity running as well? or not?

**Comment by jonassvensson4** [comment]
No you don't need it

**Comment by JessicaxD** [comment]
GETTING THIS ERROR when i try to make a character and change character: error during NUI callback NUInewCharacter: citizen:/scripting/lua/scheduler.lua_657: no such export open registry in resource esx_identity

**Comment by Emilstag** [comment]
Same error
