### ISSUE TITLE
Disable mapspawn locations

### ISSUE THREAD

**Issue by bobsnunhes** [jonassvensson4/jsfour-register#10]
Hi ! First of all thanks for share this script, it´s amazing.. 
How can i disable map spawn locations ?

**Comment by jonassvensson4** [comment]
You remove them from map.lua

If you want to remove it completely you obviously remove the whole map.lua and remove the map variable in __resource.lua

**Comment by bobsnunhes** [comment]
I already tried both things .... If i just remove the commands from map.lua or remove the file + map´s variables in __resource.lua he just give me an error saying that have invalid coords...

**Comment by jonassvensson4** [comment]
I've already explained how you remove it. Can't help you more

**Comment by bobsnunhes** [comment]
I already did what you say.... And don´t worked .... But ok, i will do my own script ...

**Comment by jonassvensson4** [comment]
Great!

**Comment by YoungJSHootaz** [comment]
> I already tried both things .... If i just remove the commands from map.lua or remove the file + map´s variables in __resource.lua he just give me an error saying that have invalid coords...

If your still having issues with you falling down thru the map disable this in 
Client.lua
Line 24

	SetEntityCollision(GetPlayerPed(-1),  false,  false)
