### ISSUE TITLE
Constant DB error with Index Value

### ISSUE THREAD

**Issue by wateredstorm** [jonassvensson4/jsfour-register#11]
Im trully sorry to be bothering you with this, but i've done it all, rebuild DB and everything.
Basically on a new host i keep getting this error and on the old one i don't.
I trully am out of ideas at this point to whats the source of the index nil value.
I've googled a lot about this to be honest aswell.

Trully appreciate any help that you can give at this point, as im out of ideas.

When i run the query in the DB it works flawless without issues which makes me even more confused. Reason to why this is such an issue is that its causing other connections to fail with the DB.

ESX_identity is down and out from the server and server.cfg, all database connections are set correct aswell, by this i mean esx_identity sql was applied indeed.

![image](https://user-images.githubusercontent.com/28515618/58744491-77d69800-843b-11e9-9fb5-539bc61a962a.png)

**Comment by jnsvns** [comment]
It looks like it can't execute the query and that's why you're getting a nil value at row 58. Is that the only error you get?

**Comment by wateredstorm** [comment]
At first yes, sometimes when this one errors out it gets me an error on
esx_skin aswell. It's really really odd.
I've tried to connect with the other dB aswell on the other server and
still displays this error.
Which confuses me deeper, as I said previously the other server runs error
free, the files are even all the same, making this even odder. 
Thank you a lot for such short time answer. I truly can't see a reason for
this.

Any help is appreciated

**Comment by wateredstorm** [comment]
So, im glad to inform you that this error is only occuring on the latest version of essentialmode.
Since i had pulled fresh on the new VPS that updated and i didn't notice.
Which implies most likely your mod won't work with the new essentialmode version.

Thanks for the reply and im sorry to be bugging you with this.

Best regards!

**Comment by jnsvns** [comment]
There are no problems with the new essentialmode. I'm pretty sure I would've gotten more issues if that was the case. I did just try the newest version on my own server and it works fine. 

I don't see what essentialmode could possible do to cause that type of error in a resource it has nothing to do with. It doesn't make any sense. 

It's a database issue for sure since it can't execute the querry and you most likely get other errors that could point you in the right direction.

Hope you manage to fix it!
