### ISSUE TITLE
Error in console

### ISSUE THREAD

**Issue by YoungJSHootaz** [jonassvensson4/jsfour-register#12]
Error running call reference function for resource jsfour-register: citizen:/scripting/lua/scheduler.lua:405: @jsfour-register/server.lua:58: attempt to index a nil value (field '?')
stack traceback:
        @jsfour-register/server.lua:58: in upvalue 'ref'
        citizen:/scripting/lua/scheduler.lua:391: in function <citizen:/scripting/lua/scheduler.lua:390>
        [C]: in function 'xpcall'
        citizen:/scripting/lua/scheduler.lua:390: in function <citizen:/scripting/lua/scheduler.lua:389>
stack traceback:
        [C]: in function 'error'
        citizen:/scripting/lua/scheduler.lua:405: in function <citizen:/scripting/lua/scheduler.lua:374>

**Comment by amasmare** [comment]
I have same error did you find any fix for it ?
