### ISSUE TITLE
Help ASAP

### ISSUE THREAD

**Issue by Bxar** [jonassvensson4/jsfour-register#6]
Hey I instaleld the script and its not popping up in game

**Comment by Bxar** [comment]
Hey It comes up in game but i press register but it does nothing

**Comment by Bxar** [comment]
This is in server console 
![image](https://user-images.githubusercontent.com/42392617/48217298-eb6d6680-e37e-11e8-93f9-73c8a6518245.png)

**Comment by jonassvensson4** [comment]
What's the name of the folder? And when do you get that error? On server startup or when you press the register button?

**Comment by Bxar** [comment]
Hey this is the name of the folder 
![image](https://user-images.githubusercontent.com/42392617/48218644-42286f80-e382-11e8-8eba-3753a479ab2a.png)

and that error appears when server is started

**Comment by jonassvensson4** [comment]
Then it's not my script that's causing that error.

The register script can't have any other name than jsfour-register

**Comment by Bxar** [comment]
Ok i shall rename the folder back to that and see if it works :)

**Comment by Bxar** [comment]
![image](https://user-images.githubusercontent.com/42392617/48221436-01345900-e38a-11e8-82ce-586ef7d70eb4.png)
this has appeared

**Comment by Bxar** [comment]
ok so i renamed it to js four register and its not appearing now in game? maybe limked to that error

**Comment by Bxar** [comment]
any idea?

**Comment by jonassvensson4** [comment]
Do you have ESX installed?

**Comment by Bxar** [comment]
yes

**Comment by jonassvensson4** [comment]
You might have messed up your start order then. The script cannot be started before ESX
