### ISSUE TITLE
Black & White Flashing

### ISSUE THREAD

**Issue by bellane** [jonassvensson4/jsfour-register#8]
When I go to create a new character I get black and white flashing in the background. I believe its the character falling through the map.

Video:
https://i.gyazo.com/9d8450743725b1f20ac72a53d58cf847.mp4

**Comment by jonassvensson4** [comment]
I mean I'm not quite sure what you want me to do about it? It's using the exact same spawn locations found in the default map scripts. As long as you've disabled them it should work fine

**Comment by bellane** [comment]
> I mean I'm not quite sure what you want me to do about it? It's using the exact same spawn locations found in the default map scripts. As long as you've disabled them it should work fine

How do I make sure they are disabled? I just enabled the script I didn't disable anything that I know of. Maybe you could point me in the right direction? Love your work! Thank you for the response.

**Comment by jonassvensson4** [comment]
You need to remove the default maps fivem-map-hipster and fivem-map-skater. Which you would've known if you could understand swedish.

**Comment by bellane** [comment]
> You need to remove the default maps fivem-map-hipster and fivem-map-skater. Which you would've known if you could understand swedish.

I removed them and it's still happening. The character is falling through the map.

**Comment by bellane** [comment]
It looks like the body isnt created until I fill out the form so there is nothing to stand on the ground which causes it to fall through the floor.

**Comment by bellane** [comment]
Getting this error as well in console.
`Error running call reference function for resource jsfour-register: citizen:/scripting/lua/scheduler.lua:403: server.lua:58: attempt to index a nil value (field '?') ` I have not modified the files at all

**Comment by jonassvensson4** [comment]
The value returns nil result[1].firstname. Check your users table in your database for null or default values.

Make sure you have ran the SQL file from esx_identity

**Comment by orloko** [comment]
> It looks like the body isnt created until I fill out the form so there is nothing to stand on the ground which causes it to fall through the floor.

just remove `SetEntityCollision(GetPlayerPed(-1),  false,  false)` from client.lua Line 24
