### ISSUE TITLE
I have a error

### ISSUE THREAD

**Issue by Emilstag** [jonassvensson4/jsfour-register#9]
After this error i got many mysql errors

Error running call reference function for resource jsfour-register: citizen:/scripting/lua/scheduler.lua:403: server.lua:58: attempt to index a nil value (field '?')
stack traceback:
        server.lua:58: in upvalue 'ref'
        citizen:/scripting/lua/scheduler.lua:389: in function <citizen:/scripting/lua/scheduler.lua:388>
        [C]: in function 'xpcall'
        citizen:/scripting/lua/scheduler.lua:388: in function <citizen:/scripting/lua/scheduler.lua:387>
stack traceback:
        [C]: in function 'error'
        citizen:/scripting/lua/scheduler.lua:403: in function <citizen:/scripting/lua/scheduler.lua:372>

**Comment by jonassvensson4** [comment]
This value returns nil `result[1].firstname`. Check your users table in your database for null or default values.

Make sure you have ran the SQL file from [esx_identity](https://github.com/ESX-Org/esx_identity)
